version: '3.8'

services:
  mongo:
    image: mongo:latest
    command: ["mongod", "--quiet"]
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app_network

  ai-model:
    build: .
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_DB_HOST=mongo
      - MONGO_DB_PORT=27017
      - MONGO_DB_NAME=visualTechDB
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
